services:
  client:
    build: ./client
    ports:
      - '8000:8000'
    volumes:
      - ./client:/app
      - /app/node_modules
    container_name: client
  server:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    container_name: server
